# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('img_id', models.CharField(max_length=200)),
                ('img_name', models.CharField(max_length=200)),
            ],
        ),
    ]
